### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by dylanjmcconnell** [fneum/spatial-sector-dashboard#3]
Just fyi - seems there's a CORS issue with the streamlit app:

Error message from the console (for landing page URL  https://h2-network.streamlit.app/) below:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://share.streamlit.io/-/auth/app?redirect_uri=https%3A%2F%2Fh2-network.streamlit.app%2Fapi%2Fv1%2Fuser. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 303.`

**Comment by fneum** [comment]
Thanks for letting me know. I just got to this, and the app was already running again.
